### PR TITLE
Add Dynamic Lights

### PR DESCRIPTION
**Pull request by PaintNinja**
Very surprised this wasn't already included!
https://www.curseforge.com/minecraft/mc-mods/dynamic-lights

### CODE REVIEW

**Comment by LambdAurora** [comment]
I'm not entirely sure I'm really happy with suggesting a mod that honestly does a pretty bad job at having smooth lighting when compared to OptiFine.

**Comment by PaintNinja** [comment]
It's similar to Optifine's "Fast" dynamic lights mode. Aside from using Optifine, there's not a lot of other options for Forge users aside from maybe shaders?

**Comment by JustAHuman-xD** [comment]
Ik there's another mod that does it in a much more performant way, can't remember its name tho

**Comment by PaintNinja** [comment]
Why did you close this PR?

**Comment by LambdAurora** [comment]
I have already stated the reason a bit higher, and #63 also happened.

**Pull request closed without merging**
