### PR TITLE
correct wording of list criterion

### PR DESCRIPTION
**Pull request by CyberFlameGO**
PVP clients aren't necessarily cheat clients, in the sense that they're not hacks. I've split the wording to specify that both PVP clients *and* cheat clients aren't allowed.

Supersedes #36 which was closed due to conflicts with the base branch being changed (I was advised that this pull request should be made against the `data` branch, which doesn't appear to be the case in the instance of this pull request's minor changes).

### CODE REVIEW

**Comment by LambdAurora** [comment]
You need to create the PR from the `data` branch.

**Comment by CyberFlameGO** [comment]
> You need to create the PR from the `data` branch.

How so? I believe the README on that branch isn't identical to the one I'm editing, unless it's named differently

**Comment by LambdAurora** [comment]
The README you're editing is auto-generated, in the data branch there's the README.in.md that is used for the auto-generation.
Which also will edit the HTML version of the list automatically.

Editing the rendered branch will always get overwritten.

**Comment by CyberFlameGO** [comment]
Ahh gotcha, thanks!

**Pull request closed without merging**
